// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btlfheiohdyltfzxobje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0bGZoZWlvaGR5bHRmenhvYmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzYyNjgsImV4cCI6MjA3MzYxMjI2OH0.TynmFgabSCjJ5edfRB92Oj0LpYfCPVRLrdQwMZOI5Gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});